version: "3.8"

services:
  nodejs_app:
    build:
      context: .
    container_name: inspet_sa_backend_app
    restart: always
    ports:
      - "8081:8081"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: pm2-runtime ecosystem.config.js